# Generated by Django 4.1.4 on 2023-08-09 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.UUIDField(db_column='id', default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Id')),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='Create Date')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updated_at', verbose_name='Update Date')),
                ('firstName', models.CharField(db_column='firstName', max_length=100, null=True, verbose_name='First Name')),
                ('lastName', models.CharField(db_column='lastName', max_length=100, null=True, verbose_name='Last Name')),
                ('email', models.EmailField(db_column='email', max_length=100, unique=True, verbose_name='Email')),
                ('password', models.CharField(db_column='password', max_length=128, null=True, verbose_name='Password')),
                ('level', models.IntegerField(choices=[(5, 5), (1, 1), (2, 2)], db_column='level', null=True, verbose_name='Level')),
                ('phoneNumber', models.CharField(db_column='phone_number', max_length=13, verbose_name='Phone Number')),
                ('profilePicture', models.URLField(db_column='profile_picture', max_length=512, null=True, verbose_name='Profile Picture')),
                ('signInMethod', models.CharField(choices=[('email', 'email'), ('google', 'google')], db_column='sign_in_method', max_length=10, verbose_name='Sign In Method')),
                ('is_active', models.BooleanField(db_column='is_active', default=False, verbose_name='Is Active')),
                ('is_staff', models.BooleanField(db_column='is_staff', default=False, verbose_name='Is Staff')),
                ('is_superuser', models.BooleanField(db_column='is_superuser', default=False, verbose_name='Is Superuser')),
                ('isVerified', models.BooleanField(db_column='is_verified', default=False, verbose_name='Is Verified')),
                ('otp', models.CharField(db_column='otp', max_length=10, null=True, verbose_name='OTP')),
                ('country', models.CharField(db_column='country', max_length=100, null=True, verbose_name='Country')),
                ('city', models.CharField(db_column='city', max_length=100, null=True, verbose_name='City')),
                ('state', models.CharField(db_column='state', max_length=100, null=True, verbose_name='State')),
                ('governmentIdURL', models.URLField(db_column='government_id_url', max_length=1024, null=True, verbose_name='Government Id Url')),
                ('idVerification', models.BooleanField(db_column='id_verification', default=False, verbose_name='Id Verification')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'user',
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UsersDevices',
            fields=[
                ('id', models.UUIDField(db_column='id', default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Id')),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='Create Date')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updated_at', verbose_name='Update Date')),
                ('deviceId', models.CharField(db_column='device_id', max_length=500, null=True, verbose_name='Device Id')),
                ('token', models.CharField(db_column='token', max_length=500, null=True, verbose_name='Token')),
                ('deviceType', models.CharField(choices=[('android', 'android'), ('ios', 'ios'), ('ipad', 'ipad'), ('web', 'web')], db_column='device_type', max_length=500, null=True, verbose_name='Device Type')),
                ('info', models.CharField(db_column='device_info', max_length=500, null=True, verbose_name='Info')),
                ('userId', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='users_devices', to=settings.AUTH_USER_MODEL, verbose_name='User Id')),
            ],
            options={
                'verbose_name_plural': 'users_device',
                'db_table': 'users_devices',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ExportData',
            fields=[
                ('id', models.UUIDField(db_column='id', default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Id')),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='Create Date')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updated_at', verbose_name='Update Date')),
                ('modelName', models.CharField(db_column='model_name', max_length=500, verbose_name='Model Name')),
                ('fileUrl', models.URLField(db_column='file_url', max_length=512, verbose_name='File Url')),
                ('userId', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='export_data', to=settings.AUTH_USER_MODEL, verbose_name='User Id')),
            ],
            options={
                'verbose_name_plural': 'export_data',
                'db_table': 'export_data',
                'managed': True,
            },
        ),
    ]
